export const DRAGGABLE_TYPE_DATA_TRANSFER_KEY = "draggable-type";

export const EDITOR_MODE_EDIT = "EDITOR_MODE_EDIT";
export const EDITOR_MODE_PREVIEW = "EDITOR_MODE_PREVIEW";

export const SCREEN_LAYOUT_TYPE_FULL_SCREEN = "SCREEN_LAYOUT_TYPE_FULL_SCREEN";
export const SCREEN_LAYOUT_TYPE_POLAROID = "SCREEN_LAYOUT_TYPE_POLAROID";
export const SCREEN_LAYOUT_TYPE_BENTO_BOX = "SCREEN_LAYOUT_TYPE_BENTO_BOX";

export const SCREEN_COMPONENT_TYPE_TEXT = "SCREEN_COMPONENT_TYPE_TEXT";
export const SCREEN_COMPONENT_TYPE_IMAGE = "SCREEN_COMPONENT_TYPE_IMAGE";
export const SCREEN_COMPONENT_TYPE_VIDEO = "SCREEN_COMPONENT_TYPE_VIDEO";
